# Generated by Django 4.0.6 on 2022-08-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='cake', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
